version: "3"

services:
  apisix:
    container_name: apisix
    build: ./apisix
    environment:
      OIDC_CLIENTID: apisix
      OIDC_SECRET: rjoVkMUDpUH4TE7IXhhJuof4O7OFrbph
      OIDC_ISSUER: http://keycloak.localhost:9009/realms/apisix
      SESSION_SECRET: idontknowwhattop
    ports:
      - "9080:9080"

  keycloak:
    container_name: keycloak
    build: ./keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9009:9009"
    networks:
      default:
        aliases: [keycloak.localhost]

  web:
    container_name: web
    build: ./web
    ports:
      - "3000:3000"
    restart: always
