version: "3"

services:
  apisix:
    container_name: apisix
    build: ./apisix
    environment:
      OIDC_CLIENTID: apisix
      OIDC_SECRET: rjoVkMUDpUH4TE7IXhhJuof4O7OFrbph
      OIDC_ISSUER: http://localhost:9080/auth/realms/apisix
      REDIRECT_URI: http://localhost:9080/callback
      SESSION_SECRET: idontknowwhattop
    ports:
      - "9080:9080"
    extra_hosts:
      localhost: 127.0.0.1
    restart: always

  keycloak:
    container_name: keycloak
    build: ./keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9009
      KC_HOSTNAME_URL: http://localhost:9080/auth/
      KC_HOSTNAME_ADMIN_URL: http://localhost:9080/auth/
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
    ports:
      - "9009:9009"
    restart: always

  web:
    container_name: web
    build: ./web
    ports:
      - "3000:3000"
    restart: always

  mock:
    container_name: mock
    image: kong/httpbin:0.1.0
    ports:
      - "7080:80"
