version: "3.7"

services:
  apisix:
    container_name: apisix
    build: ./apisix
    environment:
      KEYCLOAK_URL: http://mypi.local:9080/auth/realms/apisix
      KEYCLOAK_CLIENT_SECRET: rjoVkMUDpUH4TE7IXhhJuof4O7OFrbph
    ports:
      - "9080:9080"
      - "9433:9433"
    extra_hosts:
      mypi.local: 127.0.0.1
    restart: always

  keycloak:
    container_name: keycloak
    build: ./keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      PROXY_ADDRESS_FORWARDING: "true"
      KC_PROXY: "edge"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "9009:9009"
    restart: always

  web:
    container_name: web
    build: ./web
    ports:
      - "3000:3000"
    restart: always

volumes:
  mysql-data:
