import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-4 justify-center p-8">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/sample">Sample</Link>
            </li>
            <li>
              <Link href="/another/page">Another Page</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
